import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Next Basic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-slate-500 px-6 py-4">
          <h5>Logo</h5>
          <div className="flex gap-4">
          <ul>
            <li>Home</li>
            <li>About</li>
            <li>Contact</li>
          </ul>
          </div>

        </nav>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
